class QString;
extern double HEATING_MULTIPLIERSF;
extern double HEATING_MULTIPLIERFP;
extern double HEATING_MULTIPLIERPM;
extern double HEATING_MULTIPLIERMS;
extern double HEATING_MULTIPLIERSE;
extern QString CSVSEPARATOR;
extern QString CSVFILENAME;
extern double RESOLUTIONSCALE;
extern int COMPORT_NUMBER;
extern int BAUDRATE;
extern char TRANS_MODE[];
extern unsigned long ARDUINO_SLEEPTIMER;
extern int INTERVALL_TIMER;
extern double MOTORSPEEDHEAT;
extern double MOTORSPEEDNORMAL;
